# Generated by Django 5.2 on 2026-07-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Supports international numbers', max_length=15, unique=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('profile_pic', models.CharField(blank=True, default='default.png', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
