# Generated by Django 5.2 on 2026-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
