# Generated by Django 5.2 on 2026-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_friendlistdata_delete_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlistdata',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
