# Generated by Django 5.2 on 2026-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_friendlistdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.CharField(default='default.png', max_length=255),
        ),
    ]
