# Generated by Django 5.2 on 2026-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_userdata_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
