# Generated by Django 5.2 on 2026-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_messagedata_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.CharField(default='default_pic.png', max_length=255),
        ),
    ]
