# Generated by Django 5.2 on 2026-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_userdata_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verified_otp',
            field=models.CharField(default='######', max_length=6),
        ),
    ]
