# Generated by Django 5.2 on 2026-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_userdata_verified_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='verified_otp',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
